"""add due_date to todos

Revision ID: 2c7e80fe71c8
Revises: d873bca84447
Create Date: 2026-08-30 12:36:41.822335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7e80fe71c8'
down_revision: Union[str, Sequence[str], None] = 'd873bca84447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
